language: shell
dist: xenial
sudo: required

git:
  depth: 15

addons:
  apt:
    packages:
    - dkms

env:
  global:
    - INSTALLED_HEADERS=/tmp/installed_kernels.txt

before_install: sudo ./install.sh

install: sudo ./scripts/kernels.sh

script: sudo ./scripts/dkms_test.sh

matrix:
  fast_finish: true
